services:
  ssh-server:
    image: linuxserver/openssh-server:9.9_p1-r2-ls187
    container_name: remote_backup_server
    environment:
      - PASSWORD_ACCESS=true
      - USER_NAME=sshadmin
      - USER_PASSWORD=ssh-password
    ports:
      - "2222:2222"
    networks:
      - ocelotcloud_restic

networks:
  ocelotcloud_restic:
    external: true