services:
  xwiki:
    image: "xwiki:17.2.0-postgres-tomcat"
    container_name: ocelotcloud_xwiki_xwiki
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=password
      - DB_HOST=ocelotcloud_xwiki_db
    volumes:
      - celotcloud_xwiki_xwiki:/usr/local/xwiki

  db:
    image: "postgres:17.4-alpine"
    container_name: ocelotcloud_xwiki_db
    restart: unless-stopped
    volumes:
      - ocelotcloud_xwiki_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
